- project:
    queue: kuryr
    templates:
      - openstack-cover-jobs
      - openstack-python3-jobs
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
      - check-requirements
    gate: {}
