- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - release-notes-jobs
      - publish-openstack-sphinx-docs
      - check-requirements
    check:
      jobs:
        - openstack-tox-cover:
            voting: false
    gate:
      queue: kuryr
