#!/bin/bash
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

INT_BRIDGE="br-int"

bind_port() {
    echo "plugging veth $2 (Neutron port $1)..."
    mac=`ip link show dev $2 | tail -1 | awk '{print $2}'`
    sudo ovs-vsctl add-port $INT_BRIDGE $2
    sudo ovs-vsctl set interface $2 external_ids:attached-mac=$mac \
        external_ids:iface-id=$1 external_ids:vm-uuid=$3 \
        external_ids:iface-status=active external_ids:owner=kuryr
}

unbind_port() {
    echo "unplugging veth $1..."
    PORT=`sudo ovs-vsctl --data=bare --no-heading --columns=name \
          find interface external_ids:iface-id=$1 \
          external_ids:owner=kuryr`
    if [ -z "$PORT" ]; then
        echo >&2 "Failed to find port $1."
        exit 1
    fi
    sudo ovs-vsctl del-port $INT_BRIDGE $PORT
}

case $1 in
    "bind")
        shift
        bind_port "$@"
        exit 0
        ;;
    "unbind")
        shift
        unbind_port "$@"
        exit 0
        ;;
    *)
        echo >&2 "$0: Invalid command $1."
        exit 1
        ;;
esac
